program: train.py
method: grid
metric:
  name: best_val_acc
  goal: maximize
parameters:
  fold_num:
    values: [0]
  exec_name: # change to easily identify
    values: ["comparison: joints stream(KABR)"]
  window_size:
    values: [65]
  num_samples:
    values: [16]
  data_dir:
    values: ["data/others/KABR"]
  num_classes:
    values: [8]
  actions:
    values: [["Walk", "Graze", "Browse", "Head Up", "Auto-Groom", "Trot", "Run", "Occluded"]]
  epochs:
    values: [2000]
  patient_epochs:
    values: [500]
  batch_size:
    values: [5]
  self_training_weights_dir_name:
    values: ["KABR"]
  
  # other parameters...
  # what stream

  # is_local_flow_stream:
  #   values: [True]
  # is_i3dgcn_stream:
  #   values: [True]
  # is_X3D_stream:
  #   values: [True]
  # is_I3D_stream:
  #   values: [True]
  # I3D_mode:
  #   values: ["flow", "rgb"]
  