program: train.py
method: grid
metric:
  name: best_val_acc
  goal: maximize
parameters:
  # can only adjust, but can't delete
  exec_name: # change to easily identify
    values: ["stgcn&I3D"]
  fold_num:
    values: [0]
  # ... other parameters
  batch_size:
    values: [16]
  epochs:
    values: [100]
  add_optical_flow:
    values: [True]
  only_optical_flow:
    values: [False, True]
  