program: train.py
method: bayes
metric:
  name: best_val_acc # what we focus 
  goal: maximize # maximize the metric
parameters:
  intermidiate_channels:
    values: [32, 64]
  final_channels: 
    values: [64, 128, 256]
  learning_rate:
    distribution: log_uniform_values
    min: 3e-5
    max: 1e-3
  opt_weight_decay:
    distribution: log_uniform_values
    min: 1e-6
    max: 1e-3
  augment:
    values: [True, False]
  rot_max:
    distribution: uniform
    min: 10.0
    max: 40.0
  scale_min: 
    distribution: uniform
    min: 0.7
    max: 0.9
  scale_max:
    distribution: uniform
    min: 1.1
    max: 1.4
  joint_drop_prob:
    distribution: uniform
    min: 0.0
    max: 0.3
  frame_drop_prob:
    distribution: uniform
    min: 0.0
    max: 0.3
  shear_max:
    distribution: uniform
    min: 0.0
    max: 0.3
  temporal_jitter_prob:
    distribution: uniform
    min: 0.0
    max: 0.3
  
count: 50