program: train.py
method: grid
metric:
  name: best_val_acc
  goal: maximize
parameters:
  fold_num:
    values: [0]
  exec_name: # change to easily identify
    values: ["exp"]
  epochs:
    values: [2000]
  batch_size:
    values: [32]
  add_I3D_branch:
    values: [False]
  # other parameters...
  add_flow_adjacency:
    values: [False]
  # add_flow_stream:
  #   values: [False]