program: train.py
method: grid
metric:
  name: best_val_acc
  goal: maximize
parameters:
  exec_name: # change to easily identify
    values: ["only_optical_flow"]
  fold_num:
    values: [0]
  only_optical_flow:
    values: [True, False]